# Задачи файл "problems" 
### Выполнил студент группы БСТ1901 

## Задача 1. «Треугольник с максимальным периметром»

Массив A состоит из целых положительных чисел ­ длин отрезков. Составьте из трех отрезков такой треугольник, чтобы его периметр был максимально возможным. Если невозможно
составить треугольник с положительной площадью ­ функция возвращает 0

In [1]:
import numpy

In [2]:
def matrixgenerate():
    n=int(input())
    massiv = numpy.random.random_integers(0, 20, size=(n))
    massiv=sorted(massiv, reverse=True)
    for i, j in enumerate(massiv):
        print("massiv[", i, "]=", j)
    return massiv

In [3]:
def perimetr(massiv):
    P=0
    
    for i in range(len(massiv)-2):
        if massiv[i]<massiv[i+1]+massiv[i+2]:
            return massiv[i]+massiv[i+1]+massiv[i+2]

In [4]:
massiv=matrixgenerate()
# leng=int(input())
# massiv=[0]*leng
# for i in range(len(massiv)):
#    massiv[i]=int(input())
# sorted(massiv)
# for i, j in enumerate(massiv):
#    print("massiv[", i, "]=", j)
P=perimetr(massiv)
print(P)

 10


massiv[ 0 ]= 20
massiv[ 1 ]= 20
massiv[ 2 ]= 17
massiv[ 3 ]= 15
massiv[ 4 ]= 11
massiv[ 5 ]= 8
massiv[ 6 ]= 5
massiv[ 7 ]= 4
massiv[ 8 ]= 3
massiv[ 9 ]= 0
57


/srv/conda/envs/notebook/lib/python3.7/site-packages/ipykernel_launcher.py:3: DeprecationWarning: This function is deprecated. Please call randint(0, 20 + 1) instead
  This is separate from the ipykernel package so we can avoid doing imports until


## Задача 2. «Максимальное число»

   Дан массив неотрицательных целых чисел nums. Расположите их в таком порядке, чтобы
вместе они образовали максимально возможное число.

   **Замечание:** Результат может быть очень большим числом, поэтому представьте его как
string, а не integer.

In [12]:
def check(a,b):
    one=str(a)+str(b)
    two=str(b)+str(a)
    if int(one)>int(two):
        return True
    else:
        return False
    
def shell(massline):
    length=len(massline)
    l=length
    while l>0:
        for i in range(length-l):
            j=i
            while j>=0 and check(massline[j+l], massline[j]):
                massline[j], massline[j+l]=massline[j+l], massline[j]
                j=j-l
        l=int(l/2)
    strr=""
    for i in range(len(massline)):
        strr=strr+""+str(massline[i])
    return strr

mas1=[10,2]
mas2=[3,30,34,5,9]
mas3=[1]
mas4=[10]
mas5=[34323,3432]
print(shell(mas1))
print(shell(mas2))
print(shell(mas3))
print(shell(mas4))
print(shell(mas5))

210
9534330
1
10
343234323


## Задача 3. «Сортировка диагоналей в матрице»

Дана матрица mat размером m * n, значения ­ целочисленные. Напишите функцию, сортирующую каждую диагональ матрицы по возрастанию и возвращающую получившуюся матрицу

In [9]:
import numpy

In [10]:
m, n= map(int, input('Введите m и n:').split(' '))
massiv = numpy.random.random_integers(0, 20, size=(m, n))
print(massiv)
for i in range(0,m):
    for j in range(0,n):
        l=j
        k=i
        while k<m and l<n:
            if massiv[i][j]>massiv[k][l]:
                print ("заменяет " , massiv[k][l] ," на " , massiv[i][j] )
                massiv[i][j], massiv[k][l]=massiv[k][l], massiv[i][j]
            k=k+1
            l=l+1
print("\n")
print(massiv)

Введите m и n: 3 4


[[17  4  9 11]
 [18 19 18 17]
 [12  3 11 19]]
заменяет  11  на  17
заменяет  3  на  18
заменяет  17  на  19


[[11  4  9 11]
 [ 3 17 18 17]
 [12 18 19 19]]


/srv/conda/envs/notebook/lib/python3.7/site-packages/ipykernel_launcher.py:2: DeprecationWarning: This function is deprecated. Please call randint(0, 20 + 1) instead
  
